server.port: 8080
spring.cache:
  type: caffeine
  caffeine.spec: maximumSize=1000,expireAfterAccess=PT5M, recordStats
  cache-names: version

logging.level:
  'com.example.demo.cache.CacheStatsDebugger': debug